name: Loadouts
version: '${version}'
main: com.saratoga.loadouts.Loadouts
api-version: '1.21'
description: WeaponMechanics連携 ロードアウト管理プラグイン
author: Saratoga
depend:
  - WeaponMechanics
softdepend: []

commands:
  loadout:
    description: ロードアウト管理コマンド
    usage: /<command> <edit|save|give|list|delete>
    aliases:
      - lo
      - kit

permissions:
  # User permissions (default: true - all players can use)
  loadouts.user:
    description: ロードアウトメニューを開く
    default: true
  loadouts.edit:
    description: ロードアウトを編集する
    default: true
  loadouts.save:
    description: ロードアウトを保存する
    default: true
  loadouts.cancel:
    description: ロードアウト編集をキャンセルする
    default: true
  loadouts.give:
    description: ロードアウトを受け取る
    default: true
  loadouts.list:
    description: ロードアウト一覧を表示する
    default: true
  loadouts.delete:
    description: ロードアウトを削除する
    default: true
  loadouts.rename:
    description: ロードアウト名を変更する
    default: true
  # Admin permissions (default: op - only operators)
  loadouts.admin.open:
    description: 他プレイヤーのロードアウト画面を開く
    default: op
  loadouts.admin.global:
    description: グローバルロードアウトを編集する
    default: op
  loadouts.admin.reload:
    description: 設定をリロードする
    default: op
  loadouts.admin.syncwm:
    description: WeaponMechanicsと同期する
    default: op
  loadouts.admin.give:
    description: 管理者用Give権限（configで設定可）
    default: op
